/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jfind;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import jutils.Logger;
import org.apache.commons.lang3.tuple.Pair;
import scan.ScanSet;

/**
 *
 * @author russell.brown
 */
public class jfindFrame extends javax.swing.JFrame {

    
    ScanSet set = new ScanSet("/media/veracrypt1/stuff/scans/set6OUT");
//    ScanSet set = new ScanSet("C:\\TestEnvironments\\sync\\testset");

    // ScanSet set = new ScanSet("Z://jfind//setr");

    TextSearchTable tm;

    /**
     * Creates new form jfindFrame
     */
    public jfindFrame() {
        initComponents();
        tm = new TextSearchTable();

        ts.setModel(tm);

        ts.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (event.getValueIsAdjusting() == false) {
                    String selected = set.top + "/" + ts.getValueAt(ts.getSelectedRow(), 0).toString();
                    String file = ts.getValueAt(ts.getSelectedRow(), 1).toString();

                    loadFile(selected + "/" + file);
                }
            }

        });

        ts.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                try {
                    String selected = set.top + "/" + ts.getValueAt(ts.getSelectedRow(), 0).toString();
                    String file = ts.getValueAt(ts.getSelectedRow(), 1).toString();
                    if (e.getClickCount() == 2) {
                        System.out.println("TWO " + selected + ":" + file);

                        if (file.length() == 0) {
                            if (Desktop.isDesktopSupported()) {
                                Desktop.getDesktop().open(new File(selected));
                            }
                        } else {

               

                        }
                    }
                    if (e.getClickCount() == 1) {
                        System.out.println("ONE " + ts.getValueAt(ts.getSelectedRow(), 0).toString());
                    }
                } catch (Exception exx) {
                    Logger.Severe("Error opening " + exx.getMessage());
                }

            }
        });
    }

    private void loadFile(String p) {
        try {
            File f = new File(p);
            BufferedImage img = ImageIO.read(f);
            Image newimg = img.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(newimg);
            imgLBL.setIcon(icon);
        } catch (Exception exx) {
            Logger.Severe("Error opening " + exx.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgSrarchPNL = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        imgSrchLIST = new javax.swing.JList<>();
        textSearchPNL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textSearchTB = new javax.swing.JTextField();
        textSearchTGL = new javax.swing.JToggleButton();
        srchTextBTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ts = new javax.swing.JTable();
        imgPNL = new javax.swing.JPanel();
        imgLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgSrarchPNL.setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setText("jButton1");

        imgSrchLIST.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        imgSrchLIST.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(imgSrchLIST);

        javax.swing.GroupLayout imgSrarchPNLLayout = new javax.swing.GroupLayout(imgSrarchPNL);
        imgSrarchPNL.setLayout(imgSrarchPNLLayout);
        imgSrarchPNLLayout.setHorizontalGroup(
            imgSrarchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgSrarchPNLLayout.createSequentialGroup()
                .addGroup(imgSrarchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imgSrarchPNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        imgSrarchPNLLayout.setVerticalGroup(
            imgSrarchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imgSrarchPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textSearchPNL.setBackground(new java.awt.Color(153, 255, 51));

        jLabel1.setText("Search For:");
        jLabel1.setToolTipText("");

        textSearchTB.setToolTipText("Enter search term here");

        textSearchTGL.setText("Dir ( or File )");
        textSearchTGL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                textSearchTGLItemStateChanged(evt);
            }
        });
        textSearchTGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearchTGLActionPerformed(evt);
            }
        });

        srchTextBTN.setText("Srch");
        srchTextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchTextBTNActionPerformed(evt);
            }
        });

        ts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(ts);

        javax.swing.GroupLayout textSearchPNLLayout = new javax.swing.GroupLayout(textSearchPNL);
        textSearchPNL.setLayout(textSearchPNLLayout);
        textSearchPNLLayout.setHorizontalGroup(
            textSearchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textSearchPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textSearchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(textSearchPNLLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSearchTB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSearchTGL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srchTextBTN)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        textSearchPNLLayout.setVerticalGroup(
            textSearchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textSearchPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textSearchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textSearchTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSearchTGL)
                    .addComponent(srchTextBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        textSearchTB.getAccessibleContext().setAccessibleName("");

        imgPNL.setBackground(new java.awt.Color(204, 204, 255));

        imgLBL.setText("jLabel2");

        javax.swing.GroupLayout imgPNLLayout = new javax.swing.GroupLayout(imgPNL);
        imgPNL.setLayout(imgPNLLayout);
        imgPNLLayout.setHorizontalGroup(
            imgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imgPNLLayout.setVerticalGroup(
            imgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgSrarchPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textSearchPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(imgSrarchPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textSearchPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSearchTGLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_textSearchTGLItemStateChanged
        Logger.Info("text search toggle changed to %s", evt.toString());
    }//GEN-LAST:event_textSearchTGLItemStateChanged

    private void textSearchTGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearchTGLActionPerformed
        Logger.Info("text search action perormed %s", evt.toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchTGLActionPerformed

    private void srchTextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchTextBTNActionPerformed

        tm.Clear();

        if (textSearchTGL.isSelected()) {
            List<Pair<String, String>> res = set.matchingFiles(textSearchTB.getText(), 200);

            for (Pair<String, String> p : res) {
                tm.Add(p.getLeft(), p.getRight());
                Logger.Info("Adding " + p.getLeft() + " " + p.getRight());
            }
        } else {
            List<String> res = set.matchingDirs(textSearchTB.getText(), 200);

            for (String s : res) {
                tm.Add(s);
                Logger.Info("Adding " + s);
            }

        }

        tm.Finished();

    }//GEN-LAST:event_srchTextBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfindFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLBL;
    private javax.swing.JPanel imgPNL;
    private javax.swing.JPanel imgSrarchPNL;
    private javax.swing.JList<String> imgSrchLIST;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton srchTextBTN;
    private javax.swing.JPanel textSearchPNL;
    private javax.swing.JTextField textSearchTB;
    private javax.swing.JToggleButton textSearchTGL;
    private javax.swing.JTable ts;
    // End of variables declaration//GEN-END:variables
}
